//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Muxagot3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Метеостанция.
    /// </summary>
    // *** Start programmer edit section *** (meteo CustomAttributes)

    // *** End programmer edit section *** (meteo CustomAttributes)
    [AutoAltered()]
    [Caption("Метеостанция")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("meteoE", new string[] {
            "Широта as \'Широта\'",
            "Местоположение as \'Местоположение\'",
            "Долгота as \'Долгота\'",
            "ТекущаяТемп as \'Текущая темп\'",
            "Влажность as \'Влажность\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "Данные as \'Данные\'",
            "МетеостанцияID as \'Метеостанция ID\'"})]
    [AssociatedDetailViewAttribute("meteoE", "Xran", "XranE", true, "", "Xran", true, new string[] {
            ""})]
    [View("meteoL", new string[] {
            "Широта as \'Широта\'",
            "Местоположение as \'Местоположение\'",
            "Долгота as \'Долгота\'",
            "ТекущаяТемп as \'Текущая темп\'",
            "Влажность as \'Влажность\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "Данные as \'Данные\'",
            "МетеостанцияID as \'Метеостанция ID\'"})]
    [View("МетеостанцияE", new string[] {
            "IDИдентификатор as \'I d идентификатор\'",
            "Местоположение as \'Местоположение\'",
            "Широта as \'Широта\'",
            "Долгота as \'Долгота\'",
            "Влажность as \'Влажность\'"})]
    [View("МетеостанцияL", new string[] {
            "IDИдентификатор as \'I d идентификатор\'",
            "Местоположение as \'Местоположение\'",
            "Широта as \'Широта\'",
            "Долгота as \'Долгота\'",
            "Влажность as \'Влажность\'"})]
    public class meteo : ICSSoft.STORMNET.DataObject
    {
        
        private double fШирота;
        
        private string fМетостанция;
        
        private string fМестоположение;
        
        private double fДолгота;
        
        private double fТекущаяТемп;
        
        private double fВлажность;
        
        private int fIDИдентификатор;
        
        private string fНастройки;
        
        private string fДанные;
        
        private int fМетеостанцияID;
        
        private IIS.Muxagot3.City fCity;
        
        private IIS.Muxagot3.DetailArrayOfXran fXran;
        
        // *** Start programmer edit section *** (meteo CustomMembers)

        // *** End programmer edit section *** (meteo CustomMembers)

        
        /// <summary>
        /// IDИдентификатор.
        /// </summary>
        // *** Start programmer edit section *** (meteo.IDИдентификатор CustomAttributes)

        // *** End programmer edit section *** (meteo.IDИдентификатор CustomAttributes)
        public virtual int IDИдентификатор
        {
            get
            {
                // *** Start programmer edit section *** (meteo.IDИдентификатор Get start)

                // *** End programmer edit section *** (meteo.IDИдентификатор Get start)
                int result = this.fIDИдентификатор;
                // *** Start programmer edit section *** (meteo.IDИдентификатор Get end)

                // *** End programmer edit section *** (meteo.IDИдентификатор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.IDИдентификатор Set start)

                // *** End programmer edit section *** (meteo.IDИдентификатор Set start)
                this.fIDИдентификатор = value;
                // *** Start programmer edit section *** (meteo.IDИдентификатор Set end)

                // *** End programmer edit section *** (meteo.IDИдентификатор Set end)
            }
        }
        
        /// <summary>
        /// Влажность.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Влажность CustomAttributes)

        // *** End programmer edit section *** (meteo.Влажность CustomAttributes)
        public virtual double Влажность
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Влажность Get start)

                // *** End programmer edit section *** (meteo.Влажность Get start)
                double result = this.fВлажность;
                // *** Start programmer edit section *** (meteo.Влажность Get end)

                // *** End programmer edit section *** (meteo.Влажность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Влажность Set start)

                // *** End programmer edit section *** (meteo.Влажность Set start)
                this.fВлажность = value;
                // *** Start programmer edit section *** (meteo.Влажность Set end)

                // *** End programmer edit section *** (meteo.Влажность Set end)
            }
        }
        
        /// <summary>
        /// Данные.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Данные CustomAttributes)

        // *** End programmer edit section *** (meteo.Данные CustomAttributes)
        [StrLen(255)]
        public virtual string Данные
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Данные Get start)

                // *** End programmer edit section *** (meteo.Данные Get start)
                string result = this.fДанные;
                // *** Start programmer edit section *** (meteo.Данные Get end)

                // *** End programmer edit section *** (meteo.Данные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Данные Set start)

                // *** End programmer edit section *** (meteo.Данные Set start)
                this.fДанные = value;
                // *** Start programmer edit section *** (meteo.Данные Set end)

                // *** End programmer edit section *** (meteo.Данные Set end)
            }
        }
        
        /// <summary>
        /// Долгота.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Долгота CustomAttributes)

        // *** End programmer edit section *** (meteo.Долгота CustomAttributes)
        public virtual double Долгота
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Долгота Get start)

                // *** End programmer edit section *** (meteo.Долгота Get start)
                double result = this.fДолгота;
                // *** Start programmer edit section *** (meteo.Долгота Get end)

                // *** End programmer edit section *** (meteo.Долгота Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Долгота Set start)

                // *** End programmer edit section *** (meteo.Долгота Set start)
                this.fДолгота = value;
                // *** Start programmer edit section *** (meteo.Долгота Set end)

                // *** End programmer edit section *** (meteo.Долгота Set end)
            }
        }
        
        /// <summary>
        /// Местоположение.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Местоположение CustomAttributes)

        // *** End programmer edit section *** (meteo.Местоположение CustomAttributes)
        [StrLen(255)]
        public virtual string Местоположение
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Местоположение Get start)

                // *** End programmer edit section *** (meteo.Местоположение Get start)
                string result = this.fМестоположение;
                // *** Start programmer edit section *** (meteo.Местоположение Get end)

                // *** End programmer edit section *** (meteo.Местоположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Местоположение Set start)

                // *** End programmer edit section *** (meteo.Местоположение Set start)
                this.fМестоположение = value;
                // *** Start programmer edit section *** (meteo.Местоположение Set end)

                // *** End programmer edit section *** (meteo.Местоположение Set end)
            }
        }
        
        /// <summary>
        /// МетеостанцияID.
        /// </summary>
        // *** Start programmer edit section *** (meteo.МетеостанцияID CustomAttributes)

        // *** End programmer edit section *** (meteo.МетеостанцияID CustomAttributes)
        public virtual int МетеостанцияID
        {
            get
            {
                // *** Start programmer edit section *** (meteo.МетеостанцияID Get start)

                // *** End programmer edit section *** (meteo.МетеостанцияID Get start)
                int result = this.fМетеостанцияID;
                // *** Start programmer edit section *** (meteo.МетеостанцияID Get end)

                // *** End programmer edit section *** (meteo.МетеостанцияID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.МетеостанцияID Set start)

                // *** End programmer edit section *** (meteo.МетеостанцияID Set start)
                this.fМетеостанцияID = value;
                // *** Start programmer edit section *** (meteo.МетеостанцияID Set end)

                // *** End programmer edit section *** (meteo.МетеостанцияID Set end)
            }
        }
        
        /// <summary>
        /// Метостанция.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Метостанция CustomAttributes)

        // *** End programmer edit section *** (meteo.Метостанция CustomAttributes)
        [StrLen(255)]
        public virtual string Метостанция
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Метостанция Get start)

                // *** End programmer edit section *** (meteo.Метостанция Get start)
                string result = this.fМетостанция;
                // *** Start programmer edit section *** (meteo.Метостанция Get end)

                // *** End programmer edit section *** (meteo.Метостанция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Метостанция Set start)

                // *** End programmer edit section *** (meteo.Метостанция Set start)
                this.fМетостанция = value;
                // *** Start programmer edit section *** (meteo.Метостанция Set end)

                // *** End programmer edit section *** (meteo.Метостанция Set end)
            }
        }
        
        /// <summary>
        /// Настройки.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Настройки CustomAttributes)

        // *** End programmer edit section *** (meteo.Настройки CustomAttributes)
        [StrLen(255)]
        public virtual string Настройки
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Настройки Get start)

                // *** End programmer edit section *** (meteo.Настройки Get start)
                string result = this.fНастройки;
                // *** Start programmer edit section *** (meteo.Настройки Get end)

                // *** End programmer edit section *** (meteo.Настройки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Настройки Set start)

                // *** End programmer edit section *** (meteo.Настройки Set start)
                this.fНастройки = value;
                // *** Start programmer edit section *** (meteo.Настройки Set end)

                // *** End programmer edit section *** (meteo.Настройки Set end)
            }
        }
        
        /// <summary>
        /// ТекущаяТемп.
        /// </summary>
        // *** Start programmer edit section *** (meteo.ТекущаяТемп CustomAttributes)

        // *** End programmer edit section *** (meteo.ТекущаяТемп CustomAttributes)
        public virtual double ТекущаяТемп
        {
            get
            {
                // *** Start programmer edit section *** (meteo.ТекущаяТемп Get start)

                // *** End programmer edit section *** (meteo.ТекущаяТемп Get start)
                double result = this.fТекущаяТемп;
                // *** Start programmer edit section *** (meteo.ТекущаяТемп Get end)

                // *** End programmer edit section *** (meteo.ТекущаяТемп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.ТекущаяТемп Set start)

                // *** End programmer edit section *** (meteo.ТекущаяТемп Set start)
                this.fТекущаяТемп = value;
                // *** Start programmer edit section *** (meteo.ТекущаяТемп Set end)

                // *** End programmer edit section *** (meteo.ТекущаяТемп Set end)
            }
        }
        
        /// <summary>
        /// Широта.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Широта CustomAttributes)

        // *** End programmer edit section *** (meteo.Широта CustomAttributes)
        public virtual double Широта
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Широта Get start)

                // *** End programmer edit section *** (meteo.Широта Get start)
                double result = this.fШирота;
                // *** Start programmer edit section *** (meteo.Широта Get end)

                // *** End programmer edit section *** (meteo.Широта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Широта Set start)

                // *** End programmer edit section *** (meteo.Широта Set start)
                this.fШирота = value;
                // *** Start programmer edit section *** (meteo.Широта Set end)

                // *** End programmer edit section *** (meteo.Широта Set end)
            }
        }
        
        /// <summary>
        /// Метеостанция.
        /// </summary>
        // *** Start programmer edit section *** (meteo.City CustomAttributes)

        // *** End programmer edit section *** (meteo.City CustomAttributes)
        [PropertyStorage(new string[] {
                "City"})]
        [NotNull()]
        public virtual IIS.Muxagot3.City City
        {
            get
            {
                // *** Start programmer edit section *** (meteo.City Get start)

                // *** End programmer edit section *** (meteo.City Get start)
                IIS.Muxagot3.City result = this.fCity;
                // *** Start programmer edit section *** (meteo.City Get end)

                // *** End programmer edit section *** (meteo.City Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.City Set start)

                // *** End programmer edit section *** (meteo.City Set start)
                this.fCity = value;
                // *** Start programmer edit section *** (meteo.City Set end)

                // *** End programmer edit section *** (meteo.City Set end)
            }
        }
        
        /// <summary>
        /// Метеостанция.
        /// </summary>
        // *** Start programmer edit section *** (meteo.Xran CustomAttributes)

        // *** End programmer edit section *** (meteo.Xran CustomAttributes)
        public virtual IIS.Muxagot3.DetailArrayOfXran Xran
        {
            get
            {
                // *** Start programmer edit section *** (meteo.Xran Get start)

                // *** End programmer edit section *** (meteo.Xran Get start)
                if ((this.fXran == null))
                {
                    this.fXran = new IIS.Muxagot3.DetailArrayOfXran(this);
                }
                IIS.Muxagot3.DetailArrayOfXran result = this.fXran;
                // *** Start programmer edit section *** (meteo.Xran Get end)

                // *** End programmer edit section *** (meteo.Xran Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (meteo.Xran Set start)

                // *** End programmer edit section *** (meteo.Xran Set start)
                this.fXran = value;
                // *** Start programmer edit section *** (meteo.Xran Set end)

                // *** End programmer edit section *** (meteo.Xran Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "meteoE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View meteoE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("meteoE", typeof(IIS.Muxagot3.meteo));
                }
            }
            
            /// <summary>
            /// "meteoL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View meteoL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("meteoL", typeof(IIS.Muxagot3.meteo));
                }
            }
            
            /// <summary>
            /// "МетеостанцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МетеостанцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МетеостанцияE", typeof(IIS.Muxagot3.meteo));
                }
            }
            
            /// <summary>
            /// "МетеостанцияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МетеостанцияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МетеостанцияL", typeof(IIS.Muxagot3.meteo));
                }
            }
        }
    }
}
