




CREATE TABLE City (
 primaryKey UUID NOT NULL,
 Название VARCHAR(255) NULL,
 Широта DOUBLE PRECISION NULL,
 IDИдентификатор INT NULL,
 Долгота DOUBLE PRECISION NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Xran (
 primaryKey UUID NOT NULL,
 IDИдентификатор INT NULL,
 Настройки VARCHAR(255) NULL,
 Данные VARCHAR(255) NULL,
 МетеостанцияID INT NULL,
 meteo UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE meteo (
 primaryKey UUID NOT NULL,
 Широта DOUBLE PRECISION NULL,
 Метостанция VARCHAR(255) NULL,
 Местоположение VARCHAR(255) NULL,
 Долгота DOUBLE PRECISION NULL,
 ТекущаяТемп DOUBLE PRECISION NULL,
 Влажность DOUBLE PRECISION NULL,
 IDИдентификатор INT NULL,
 Настройки VARCHAR(255) NULL,
 Данные VARCHAR(255) NULL,
 МетеостанцияID INT NULL,
 City UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE home (
 primaryKey UUID NOT NULL,
 Имя VARCHAR(255) NULL,
 Адрес VARCHAR(255) NULL,
 Долгота DOUBLE PRECISION NULL,
 Широта DOUBLE PRECISION NULL,
 City UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Xran ADD CONSTRAINT FKdb33c25ee433859ffa7679492dffc406d8a46776 FOREIGN KEY (meteo) REFERENCES meteo; 
CREATE INDEX Indexdb33c25ee433859ffa7679492dffc406d8a46776 on Xran (meteo); 

 ALTER TABLE meteo ADD CONSTRAINT FK632c9bfa157c239846d53b769f0e8c3a1dd682ec FOREIGN KEY (City) REFERENCES City; 
CREATE INDEX Index632c9bfa157c239846d53b769f0e8c3a1dd682ec on meteo (City); 

 ALTER TABLE home ADD CONSTRAINT FK51741186f8e8fdcbf600e7e12e1920610176aa42 FOREIGN KEY (City) REFERENCES City; 
CREATE INDEX Index51741186f8e8fdcbf600e7e12e1920610176aa42 on home (City); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

